ALTER TABLE notes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE note_versions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE note_links NO FORCE ROW LEVEL SECURITY;
ALTER TABLE comments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE note_tags NO FORCE ROW LEVEL SECURITY;
