ALTER TABLE workspace_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE notebooks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE notebook_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tags NO FORCE ROW LEVEL SECURITY;
ALTER TABLE notebook_tags NO FORCE ROW LEVEL SECURITY;
ALTER TABLE invitations NO FORCE ROW LEVEL SECURITY;
