package com.notebook.lumen.identity.admin.retention;

import java.util.Comparator;
import java.util.List;
import org.springframework.stereotype.Component;

@Component
public class RetentionTargetRegistry {

  private final List<RetentionTargetDefinition> targets =
      List.of(
          target(
              "content.workspaces",
              "workspace-service",
              "Workspaces",
              "Workspace metadata and membership root records.",
              RetentionDataClass.CONTENT,
              null,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.CRITICAL,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "content.notebooks",
              "workspace-service",
              "Notebooks",
              "Notebook containers and ordering metadata.",
              RetentionDataClass.CONTENT,
              null,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "content.notes",
              "content-service",
              "Notes",
              "Current note records and note body content.",
              RetentionDataClass.CONTENT,
              null,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.CRITICAL,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "content.note_versions",
              "content-service",
              "Note versions",
              "Historical note versions used for recovery and conflict review.",
              RetentionDataClass.CONTENT,
              365,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "content.comments",
              "content-service",
              "Comments",
              "Note comment threads and comment metadata.",
              RetentionDataClass.CONTENT,
              365,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "content.search_documents",
              "content-service",
              "Content search documents",
              "Content-side search outbox/derived rows used for incremental indexing.",
              RetentionDataClass.CONTENT,
              90,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.MEDIUM,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "content.attachments_media",
              "object-storage",
              "Attachments / media",
              "Future object storage backed attachments and media.",
              RetentionDataClass.CONTENT,
              null,
              true,
              false,
              false,
              true,
              RetentionRiskLevel.CRITICAL,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "search.documents",
              "search-service",
              "Search documents",
              "Derived search index documents and permission snapshots.",
              RetentionDataClass.CONTENT,
              90,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.MEDIUM,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "identity.users",
              "identity-service",
              "Users",
              "User identity records and lifecycle state.",
              RetentionDataClass.IDENTITY,
              null,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.CRITICAL,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "identity.external_identities",
              "identity-service",
              "External identities",
              "SSO identity links and provider subject mappings.",
              RetentionDataClass.IDENTITY,
              null,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "identity.scim_users_groups",
              "identity-service",
              "SCIM users / groups",
              "SCIM user source links, groups, and memberships.",
              RetentionDataClass.IDENTITY,
              null,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "identity.scim_sync_runs",
              "identity-service",
              "SCIM sync runs / checkpoints",
              "SCIM delta diagnostics history and checkpoint metadata.",
              RetentionDataClass.IDENTITY,
              180,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.MEDIUM,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "identity.sessions_refresh_tokens",
              "identity-service",
              "Sessions / refresh tokens",
              "Refresh token session rows and revocation metadata.",
              RetentionDataClass.IDENTITY,
              90,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "audit.events",
              "identity/content/notification services",
              "Audit events",
              "Security and compliance audit events.",
              RetentionDataClass.AUDIT_SECURITY,
              365,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.CRITICAL,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "audit.break_glass_events",
              "identity-service",
              "Break-glass events",
              "Break-glass access/review/rotation governance events.",
              RetentionDataClass.AUDIT_SECURITY,
              365,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.CRITICAL,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "audit.admin_change_requests",
              "identity-service",
              "Admin change requests",
              "Admin governance requests, approvals, and GitOps proposals.",
              RetentionDataClass.AUDIT_SECURITY,
              180,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "audit.admin_rbac_overrides",
              "identity-service",
              "Admin RBAC overrides",
              "Mounted GitOps override assignments and validation history.",
              RetentionDataClass.AUDIT_SECURITY,
              null,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "identity.mfa_webauthn_metadata",
              "identity-service",
              "MFA / WebAuthn metadata",
              "Credential metadata and recovery-code lifecycle state.",
              RetentionDataClass.AUDIT_SECURITY,
              null,
              true,
              false,
              true,
              true,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.INVENTORY_ONLY),
          target(
              "notification.analytics_hourly",
              "notification-service",
              "Notification analytics (hourly)",
              "Derived hourly notification delivery analytics aggregates.",
              RetentionDataClass.NOTIFICATION,
              90,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.LOW,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "notification.fanout_outbox_sent",
              "notification-service",
              "Fanout outbox (sent)",
              "Terminal SENT notification fanout outbox rows past retention.",
              RetentionDataClass.NOTIFICATION,
              7,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.MEDIUM,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "notification.fanout_outbox_dead",
              "notification-service",
              "Fanout outbox (dead)",
              "Terminal DEAD notification fanout outbox dead-letter rows past retention.",
              RetentionDataClass.NOTIFICATION,
              90,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "notification.dead_letter_requeue_requests",
              "notification-service",
              "Dead-letter requeue requests",
              "Dead-letter requeue request audit rows past retention.",
              RetentionDataClass.NOTIFICATION,
              90,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.MEDIUM,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "notification.digest_items_terminal",
              "notification-service",
              "Digest items (terminal)",
              "Terminal SENT/CANCELLED notification digest items past retention.",
              RetentionDataClass.NOTIFICATION,
              90,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.LOW,
              RetentionTargetStatus.DRY_RUN_READY),
          target(
              "notification.email_notifications_terminal",
              "notification-service",
              "Email notifications (terminal)",
              "Terminal SENT/FAILED/CANCELLED/SKIPPED email notification rows past retention.",
              RetentionDataClass.NOTIFICATION,
              90,
              true,
              false,
              true,
              false,
              RetentionRiskLevel.HIGH,
              RetentionTargetStatus.DRY_RUN_READY));

  public List<RetentionTargetDefinition> targets() {
    return targets.stream()
        .sorted(Comparator.comparing(RetentionTargetDefinition::targetKey))
        .toList();
  }

  private static RetentionTargetDefinition target(
      String targetKey,
      String service,
      String displayName,
      String description,
      RetentionDataClass dataClass,
      Integer defaultRetentionDays,
      boolean legalHoldSupported,
      boolean destructivePurgeSupported,
      boolean dryRunSupported,
      boolean archiveRequiredBeforePurge,
      RetentionRiskLevel riskLevel,
      RetentionTargetStatus status) {
    return new RetentionTargetDefinition(
        targetKey,
        service,
        displayName,
        description,
        dataClass,
        defaultRetentionDays,
        legalHoldSupported,
        destructivePurgeSupported,
        dryRunSupported,
        archiveRequiredBeforePurge,
        riskLevel,
        status);
  }
}
