services:
  prometheus:
    image: prom/prometheus:v2.55.1
    profiles:
      - observability
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.113.0
    profiles:
      - observability
    command:
      - --config=/etc/otelcol/config.yml
    volumes:
      - ./observability/otel-collector-config.yml:/etc/otelcol/config.yml:ro
    ports:
      - "4318:4318"
