package com.notebook.lumen.gateway.error;

public enum ErrorCode {
  MISSING_ACCESS_TOKEN,
  INVALID_ACCESS_TOKEN,
  EXPIRED_ACCESS_TOKEN,
  INVALID_TOKEN_TYPE,
  INVALID_WORKSPACE_ID,
  RATE_LIMIT_EXCEEDED,
  ROUTE_UNAVAILABLE,
  INTERNAL_GATEWAY_ERROR
}
