package com.notebook.lumen.gateway.error;

public enum ErrorCode {
  MISSING_ACCESS_TOKEN,
  COOKIE_ACCESS_TOKEN_REQUIRED,
  INVALID_ACCESS_TOKEN,
  EXPIRED_ACCESS_TOKEN,
  INVALID_TOKEN_TYPE,
  CSRF_TOKEN_REQUIRED,
  CSRF_TOKEN_INVALID,
  INVALID_AUTH_TRANSPORT,
  INVALID_WORKSPACE_ID,
  ADMIN_ACCESS_DENIED,
  ADMIN_AUDIT_DISABLED,
  INVALID_AUDIT_SOURCE,
  INVALID_AUDIT_FILTER,
  AUDIT_SOURCE_UNAVAILABLE,
  AUDIT_PROXY_INTERNAL_AUTH_FAILED,
  AUDIT_PROXY_REQUEST_FAILED,
  RATE_LIMIT_EXCEEDED,
  ROUTE_UNAVAILABLE,
  INTERNAL_GATEWAY_ERROR
}
