package com.notebook.lumen.gateway.error;

public enum ErrorCode {
  MISSING_ACCESS_TOKEN,
  COOKIE_ACCESS_TOKEN_REQUIRED,
  INVALID_ACCESS_TOKEN,
  EXPIRED_ACCESS_TOKEN,
  INVALID_TOKEN_TYPE,
  CSRF_TOKEN_REQUIRED,
  CSRF_TOKEN_INVALID,
  INVALID_AUTH_TRANSPORT,
  INVALID_WORKSPACE_ID,
  RATE_LIMIT_EXCEEDED,
  ROUTE_UNAVAILABLE,
  INTERNAL_GATEWAY_ERROR
}
