/// <reference types="vite/client" />
/// <reference types="vite-plugin-pwa/client" />

interface ImportMetaEnv {
  readonly VITE_API_BASE_URL?: string
  readonly VITE_AUTH_TRANSPORT?: string
  readonly VITE_SSO_ENABLED?: string
  readonly VITE_NOTIFICATIONS_ENABLED?: string
  readonly VITE_PWA_ENABLED?: string
  readonly VITE_OFFLINE_NOTES_ENABLED?: string
  readonly VITE_OFFLINE_NOTES_MAX_ITEMS?: string
  readonly VITE_NOTIFICATION_PREFERENCES_ENABLED?: string
  readonly VITE_MFA_UI_ENABLED?: string
  readonly VITE_ADMIN_UI_ENABLED?: string
  readonly VITE_ADMIN_UI_DEV_OPEN?: string
  readonly VITE_AUDIT_API_MODE?: string
  readonly VITE_ENTERPRISE_ADMIN_WRITE_ENABLED?: string
  readonly VITE_ENTERPRISE_ADMIN_APPROVALS_ENABLED?: string
  readonly VITE_ENTERPRISE_GITOPS_PR_ENABLED?: string
  readonly VITE_GITOPS_RBAC_ROLE_REQUESTS_ENABLED?: string
  readonly VITE_ADMIN_RBAC_UI_ENABLED?: string
  readonly VITE_ADMIN_RBAC_ROLE_REQUESTS_ENABLED?: string
  readonly VITE_ADMIN_RBAC_OVERRIDES_STATUS_ENABLED?: string
  readonly VITE_ADMIN_RBAC_OVERRIDES_RELOAD_ENABLED?: string
  readonly VITE_SCIM_COMPATIBILITY_DIAGNOSTICS_ENABLED?: string
  readonly VITE_PLATFORM_RETENTION_GOVERNANCE_ENABLED?: string
  readonly VITE_BREAK_GLASS_REVIEW_UI_ENABLED?: string
  readonly VITE_BREAK_GLASS_REVOCATION_UI_ENABLED?: string
  readonly VITE_BREAK_GLASS_ROTATION_UI_ENABLED?: string
  readonly VITE_NOTIFICATION_ANALYTICS_UI_ENABLED?: string
  readonly VITE_NOTIFICATION_DEAD_LETTER_UI_ENABLED?: string
  readonly VITE_NOTIFICATION_RETENTION_UI_ENABLED?: string
  readonly VITE_NOTIFICATION_RETENTION_PURGE_UI_ENABLED?: string
  readonly VITE_NOTIFICATION_LEGAL_HOLD_UI_ENABLED?: string
  readonly VITE_SOURCEMAP?: string
  readonly VITE_OFFLINE_EDIT_ENABLED?: string
  readonly VITE_OFFLINE_SYNC_ENABLED?: string
  readonly VITE_OFFLINE_EDIT_MAX_DRAFTS?: string
  readonly VITE_OFFLINE_EDIT_MAX_DRAFT_AGE_DAYS?: string
  readonly VITE_OFFLINE_ENCRYPTION_ENABLED?: string
  readonly VITE_OFFLINE_DRAFT_ENCRYPTION_REQUIRED?: string
  readonly VITE_OFFLINE_CACHE_ENCRYPTION_ENABLED?: string
  readonly VITE_OFFLINE_SYNC_ROLLOUT_MODE?: string
  readonly VITE_OFFLINE_SYNC_MAX_ATTEMPTS?: string
  readonly VITE_OFFLINE_SYNC_STALE_MINUTES?: string
  readonly VITE_OFFLINE_BACKGROUND_SYNC_ENABLED?: string
  readonly VITE_OFFLINE_BACKGROUND_SYNC_MODE?: string
  readonly VITE_OFFLINE_BACKGROUND_SYNC_MAX_BATCH?: string
  readonly VITE_OFFLINE_BACKGROUND_SYNC_MIN_INTERVAL_SECONDS?: string
  readonly VITE_OFFLINE_BACKGROUND_SYNC_REQUIRE_UNMETERED?: string
  readonly VITE_OFFLINE_BACKGROUND_SYNC_REQUIRE_CHARGING?: string
  readonly VITE_SW_BACKGROUND_SYNC_ENABLED?: string
  readonly VITE_SW_BACKGROUND_SYNC_DRY_RUN_ONLY?: string
  readonly VITE_SW_BACKGROUND_SYNC_REGISTER_ENABLED?: string
  readonly VITE_SW_BACKGROUND_SYNC_MAX_BATCH?: string
  readonly VITE_SW_BACKGROUND_SYNC_REQUIRE_ENCRYPTION_KEY?: string
  readonly VITE_BACKEND_MERGE_ANALYSIS_ENABLED?: string
  readonly VITE_BACKEND_MERGE_APPLY_ENABLED?: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
