{{- if and (eq .Values.secrets.mode "native-kubernetes-secret") .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notebook-platform.secretName" . }}
  namespace: {{ include "notebook-platform.namespace" . }}
  labels:
    {{- include "notebook-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  identity-db-password: {{ .Values.secrets.data.identityDbPassword | quote }}
  workspace-db-runtime-password: {{ .Values.secrets.data.workspaceRuntimeDbPassword | quote }}
  workspace-db-migration-password: {{ .Values.secrets.data.workspaceMigrationDbPassword | quote }}
  content-db-runtime-password: {{ .Values.secrets.data.contentRuntimeDbPassword | quote }}
  content-db-migration-password: {{ .Values.secrets.data.contentMigrationDbPassword | quote }}
  redis-password: {{ .Values.secrets.data.redisPassword | quote }}
  otel-auth-token: {{ .Values.secrets.data.otelExporterOtlpHeaders | quote }}
  internal-api-token-primary: {{ .Values.secrets.data.internalApiTokenPrimary | quote }}
  internal-api-token-secondary: {{ .Values.secrets.data.internalApiTokenSecondary | quote }}
  workspace-internal-api-token-primary: {{ .Values.secrets.data.workspaceInternalApiTokenPrimary | quote }}
  workspace-internal-api-token-secondary: {{ .Values.secrets.data.workspaceInternalApiTokenSecondary | quote }}
  jwt-private-key.pem: {{ .Values.secrets.data.jwtPrivateKeyPem | quote }}
  jwt-public-key.pem: {{ .Values.secrets.data.jwtPublicKeyPem | quote }}
  content-service-jwt-private-key.pem: {{ .Values.secrets.data.serviceJwtPrivateKeyPem | quote }}
  content-service-jwt-public-key.pem: {{ .Values.secrets.data.serviceJwtPublicKeyPem | quote }}
{{- end }}
