{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notebook-platform.componentName" (dict "root" . "component" "frontend") }}
  namespace: {{ include "notebook-platform.namespace" . }}
  labels:
    {{- include "notebook-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "notebook-platform.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
